travis:
  secure:
    BINSTAR_TOKEN: q3ByKcHe3R/FBjvOycBH5TJ/X2OwGg+LVZbXfHQ/ThpwemsekRa85uqqZapo2SRXA7LxJRyue/wKqlJIfXoYZ0FGr9JZZIL6PHTZIiyby0c+OwleBXh79/eRh08I2+BM3zM6OupY0ArmW34KJzD9KXNSaNuElAG6GCGvZVZB1j2rzrdt1sGABJJ2jCspUtcF6na2G25ifJs5SVO/jd6aw6QkQ69B5xp3h/C61b0eM+tDANu2gx8w7RgImc9ODPZGMtNuaz5IStNyt+dPJVNaJLxSd627LaO0hNi9CNPt1AveVtbSQEFHARSNlRCPwRlE6FMEcmIsW2fI1SbbQbrBSc665e+qDa9EBd3DY30K3GyMJHM+utHgFisDQttKyUaLFhw3AhrAsMwd6e39zPlEsoM6t4ElpwUOu0XEFkNF85V9d7qUz7KxBcTYGCqxRq1CwJBwTbYZAsxll2AD6DRXAOF06M9EvJddLJaPtlkDk0zW3HP9F9S8NMHJBOyypCr3Fl1I7MD3fAyW5szAvOPUYlz3OZKt0pubocqPQxrYwsrFCUk1FJjQ3wCEqcwzC9t/gnfHD1sZ66V/MBxUEjw/hzpg7fyswqP2rxTWgj9X6O6loXRv7y06J0iJ7z7+0B8WDMU9WVYxhB/4Zm3+iKjwEadc8K+9baDfrPW3DtLFOeE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
